version: "2.0"

services:
  
  spacy-lt-tagger:
    image: "lingsoft/spacy-lt:3.3.1-elg"
    environment: []
    restart: always

  restserver:
    image: registry.gitlab.com/european-language-grid/ilsp/elg-lt-service-execution-all:production-reactive
    command:
    - "--spring.webflux.base-path=/execution"
    - "--logging.level.elg.ltserviceexecution.api=WARN"
    - "--elg.ltservices.staticServices.spacy-lt-tagger=http://spacy-lt-tagger:8000/process/tagger"
    - "--elg.base.url=http://localhost:5080/execution"
    restart: always

  egistry_gitlab_com_european_language_grid_usfd_gui_ie_latest:
    image: "registry.gitlab.com/european-language-grid/usfd/gui-ie:latest"
    restart: always

  i18n:
    image: registry.gitlab.com/european-language-grid/platform/i18n-service:latest
    restart: always

  frontend:
    image: "nginx:alpine"
    ports:
    - "5080:80"
    volumes:
    - ./nginx-conf:/etc/nginx/templates
    restart: always
